SiteTitle: Foot in the door!

NewToAustralia: New to Australia
Mentor: Be a mentor
Hiring: Discover skilled workers

Name: Anya
Profession: Software Developer

TestimonialFromPreviousUser_Header: Meet Lily…

TestimonialFromPreviousUser_Body: Thanks to this platform and the resources it provided, I was able to put my best foot forward! My mentor was able to advise me on how to present myself to the Australian job market in a way that I could relate. The company I interned with was able to quickly assess my potential and offered me a permanent position immediately after.
